{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "gitlab.fullname" .) }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  gitlab-secrets.json: {{ "{}" | b64enc | quote }}
{{- end }}
