apiVersion: v2
type: application
name: homer
description: A Helm chart for Kubernetes
version: 0.2.0
appVersion: "v22.08.1"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/homer
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/bastienwirtz/homer
keywords:
  - dashboard
  - homer
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
