# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: homer
description: A Helm chart for Kubernetes
version: 1.0.3
# renovate: image=b4bz/homer
appVersion: "v23.02.2"

home: https://charts.pascaliske.dev/charts/homer/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/bastienwirtz/homer
keywords:
  - dashboard
  - homer
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.0.2
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: 'Upgrade app to v23.02.2'
