{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
{{- if empty .Values.secret.password -}}
  {{- fail "Missing password from \".Values.secret.password\"!" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-password" (include "code-server.fullname" .) }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc }}
{{- end -}}
