apiVersion: v2
type: application
name: code-server
description: A Helm chart for Kubernetes
version: 0.3.5
appVersion: "4.8.3"

home: https://charts.pascaliske.dev/charts/code-server/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/coder/code-server
keywords:
  - vscode
  - code-server
  - browser-ide
  - ide
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
