apiVersion: v2
type: application
name: code-server
description: A Helm chart for Kubernetes
version: 0.1.1
appVersion: "v4.0.2"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/code-server
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/coder/code-server
keywords:
  - vscode
  - code-server
  - browser-ide
  - ide
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
