# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: code-server
description: A Helm chart for Kubernetes
version: 1.0.2
# renovate: image=codercom/code-server
appVersion: "4.10.1"

home: https://charts.pascaliske.dev/charts/code-server/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/coder/code-server
keywords:
  - vscode
  - code-server
  - browser-ide
  - ide
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.0.2
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: 'Use correct claim name and controller kind values'
