apiVersion: v2
type: application
name: digitalocean-dyndns
description: A Helm chart for a CronJob based DigitalOcean DynDNS client.
version: 0.0.5
appVersion: "7.75.0"

home: https://github.com/pascaliske/helm-charts
sources:
  - https://github.com/pascaliske/helm-charts
keywords:
  - digitalocean
  - dyndns
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

