{{- if .Values.controller.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hammond.fullname" . }}
  labels:
    {{- include "hammond.labels" . | nindent 4 }}
    {{- with .Values.controller.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.controller.replicas }}
  replicas: {{ .Values.controller.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hammond.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hammond.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hammond.serviceAccountName" . }}
      {{- if eq (include "base.persistence.enabled" . ) "true" }}
      initContainers:
        - name: init-volumes
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'mkdir -p {{ .Values.persistentVolumeClaim.mountPath }}/config {{ .Values.persistentVolumeClaim.mountPath }}/assets']
          volumeMounts:
            - name: {{ include "base.persistence.suffix" (include "hammond.fullname" . ) }}
              mountPath: {{ required "Mandatory value .Values.persistentVolumeClaim.mountPath is empty!" .Values.persistentVolumeClaim.mountPath }}
      {{- end }}
      containers:
        - name: {{ template "hammond.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.ports.http.enabled }}
            - name: http
              containerPort: {{ .Values.ports.http.port }}
              protocol: {{ default "TCP" .Values.ports.http.protocol | quote }}
            {{- end }}
          env:
            {{- range $i, $val := .Values.env }}
            {{- if $val.value }}
            - name: {{ $val.name | quote }}
              value: {{ $val.value | quote }}
            {{- else if $val.valueFrom }}
            - name: {{ $val.name | quote }}
              valueFrom:
                {{- toYaml $val.valueFrom | nindent 16 }}
            {{- end }}
            {{- end }}
            {{- if eq (include "base.persistence.enabled" . ) "true" }}
            {{- if not (empty .Values.persistentVolumeClaim.mountPath) }}
            - name: CONFIG
              value: {{ .Values.persistentVolumeClaim.mountPath }}/config
            - name: DATA
              value: {{ .Values.persistentVolumeClaim.mountPath }}/assets
            {{- end }}
            {{- end }}
          {{- if eq (include "base.persistence.enabled" . ) "true" }}
          volumeMounts:
            - name: {{ include "base.persistence.suffix" (include "hammond.fullname" . ) }}
              mountPath: {{ required "Mandatory value .Values.persistentVolumeClaim.mountPath is empty!" .Values.persistentVolumeClaim.mountPath }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {{ if not .Values.resources -}}{}{{- end }}
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      {{- if eq (include "base.persistence.enabled" . ) "true" }}
      {{- if eq (include "base.persistence.type" . ) "volumes" }}
      volumes:
        - name: {{ include "base.persistence.suffix" (include "hammond.fullname" . ) }}
          persistentVolumeClaim:
            {{- if eq (include "base.persistence.created" . ) "true" }}
            claimName: {{ include "base.persistence.suffix" (include "hammond.fullname" . ) }}
            {{- else }}
            claimName: {{ .Values.persistentVolumeClaim.existingPersistentVolumeClaim }}
            {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
