# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: traefik-errors
description: A Helm chart for custom traefik error pages
version: 3.0.0
# renovate: image=ghcr.io/pascaliske/traefik-errors
appVersion: "1.0.5"

home: https://charts.pascaliske.dev/charts/traefik-errors/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/pascaliske/docker-traefik-errors
keywords:
  - traefik-errors
  - traefik
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.0.1
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: 'Controller values are now configured using `controller: {}`'
