# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: paperless
description: A Helm chart for paperless-ngx
version: 4.0.1
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: "1.13.0"

home: https://charts.pascaliske.dev/charts/paperless/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/paperless-ngx/paperless-ngx
keywords:
  - paperless
  - paperless-ngx
  - document-management-system
  - dms
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.1.0
    repository: https://charts.pascaliske.dev
  - name: redis
    version: 1.1.2
    repository: https://charts.pascaliske.dev
    condition: redis.enabled

annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: 'Use correct empty default value'
