# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: prometheus
description: A Helm chart for prometheus
version: 1.3.7
# renovate: image=prom/prometheus
appVersion: "v2.42.0"
deprecated: true

home: https://charts.pascaliske.dev/charts/prometheus/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/prometheus/prometheus
  - https://prometheus.io
keywords:
  - prometheus
  - metrics
