{{- if .Values.service.enabled -}}
{{- if not (or .Values.ports.api.enabled .Values.ports.frontend.enabled) -}}
  {{- fail "All ports are disabled - at least one of \"api, frontend\" needs to be enabled!" -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-web" (include "vikunja.fullname" . ) }}
  labels:
    {{- include "vikunja.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.ports.api.enabled }}
    - name: api
      port: {{ .Values.ports.api.port }}
      targetPort: api
      {{- if and (eq $.Values.service.type "NodePort") .Values.ports.api.nodePort }}
      nodePort: {{ .Values.ports.api.nodePort }}
      {{- end }}
      protocol: {{ default "TCP" .Values.ports.api.protocol | quote }}
    {{- end }}
    {{- if .Values.ports.frontend.enabled }}
    - name: frontend
      port: {{ .Values.ports.frontend.port }}
      targetPort: frontend
      {{- if and (eq $.Values.service.type "NodePort") .Values.ports.frontend.nodePort }}
      nodePort: {{ .Values.ports.frontend.nodePort }}
      {{- end }}
      protocol: {{ default "TCP" .Values.ports.frontend.protocol | quote }}
    {{- end }}
  selector:
    {{- include "vikunja.selectorLabels" . | nindent 4 }}
{{- end }}
