# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: vikunja
description: A Helm chart for Kubernetes
version: 3.0.4
# renovate: image=vikunja/api
appVersion: "0.20.4"

home: https://charts.pascaliske.dev/charts/vikunja/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://code.vikunja.io
  - https://vikunja.io
keywords:
  - vikunja
  - todos
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.1.1
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
