apiVersion: v2
type: application
name: gitlab
description: A Helm chart for GitLab Omnibus
version: 1.3.8
# renovate: image=gitlab/gitlab-ce
appVersion: "15.8.1-ce.0"

home: https://charts.pascaliske.dev/charts/gitlab/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://docs.gitlab.com
keywords:
  - gitlab
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
