# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: gitlab
description: A Helm chart for GitLab Omnibus
version: 2.0.4
# renovate: image=gitlab/gitlab-ce
appVersion: "15.9.3-ce.0"

home: https://charts.pascaliske.dev/charts/gitlab/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://docs.gitlab.com
keywords:
  - gitlab
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.0.2
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: 'Use correct empty default value'
