image:
  repository: gitlab/gitlab-ce
  tag: 14.4.1-ce.0
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  annotations: {}
  labels: {}

service:
  enabled: true
  type: ClusterIP
  annotations: {}
  labels: {}

env:
  - name: TZ
    value: UTC

ports:
  http:
    enabled: true
    port: 80
    nodePort: null
    protocol: TCP

configMap:
  create: true
  existingConfigMap: ''
  key: gitlab.rb
  config: |
    # external_url 'https://gitlab.example.com'
  annotations: {}
  labels: {}

healthCheck:
  enabled: true
  whitelist:
    - 127.0.0.1

persistentVolumeClaims:
  - name: secrets
    create: true
    mountPath: /etc/gitlab
    existingPersistentVolumeClaim: ''
    size: 128Mi
    annotations: {}
    labels: {}
  - name: storage
    create: true
    mountPath: /var/opt/gitlab
    existingPersistentVolumeClaim: ''
    size: 30Gi
    annotations: {}
    labels: {}

backups:
  enabled: true
  mountPath: /backups
  hostPath: ''

serviceAccount:
  name: ''

securityContext: {}
  # fsGroup: 1000
  # runAsNonRoot: true
  # runAsGroup: 1000
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
