# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: uptime-kuma
description: A Helm chart for Kubernetes
version: 1.0.0
# renovate: image=louislam/uptime-kuma
appVersion: "1.20.1"

home: https://charts.pascaliske.dev/charts/uptime-kuma/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/louislam/uptime-kuma
keywords:
  - uptime
  - uptime-kuma
  - monitoring
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.0.1
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: 'Add missing PVC values and conditionals'
