apiVersion: v2
type: application
name: uptime-kuma
description: A Helm chart for Kubernetes
version: 0.3.2
appVersion: "1.18.4"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/uptime-kuma
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/louislam/uptime-kuma
keywords:
  - uptime
  - uptime-kuma
  - monitoring
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
