{{- if .Values.cronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "digitalocean-dyndns.fullname" . }}
  labels:
    {{- include "digitalocean-dyndns.labels" . | nindent 4 }}
    {{- with .Values.cronJob.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.cronJob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ include "digitalocean-dyndns.schedule" . }}
  suspend: {{ .Values.cronJob.suspend }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  jobTemplate:
    {{- with .Values.cronJob.annotations }}
    metadata:
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ template "digitalocean-dyndns.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range $i, $val := .Values.env }}
                - name: {{ $val.name | quote }}
                  value: {{ $val.value | quote }}
                {{- end }}
              envFrom:
                - secretRef:
                    {{- if and .Values.secret.create (empty .Values.secret.existingSecret) }}
                    name: {{ printf "%s-token" (include "digitalocean-dyndns.fullname" . ) }}
                    {{- else }}
                    name: {{ .Values.secret.existingSecret }}
                    {{- end }}
              command:
                - /bin/sh
                - {{ printf "/scripts/%s" (include "digitalocean-dyndns.scriptName" . ) }}
              volumeMounts:
                - name: {{ printf "%s-updater" (include "digitalocean-dyndns.fullname" . ) }}
                  mountPath: {{ printf "/scripts/%s" (include "digitalocean-dyndns.scriptName" . ) }}
                  subPath: {{ template "digitalocean-dyndns.scriptName" . }}
                  readOnly: true
              resources: {{ if not .Values.resources -}}{}{{- end }}
                {{- if .Values.resources }}
                {{- toYaml .Values.resources | nindent 16 }}
                {{- end }}
          volumes:
            - name: {{ printf "%s-updater" (include "digitalocean-dyndns.fullname" . ) }}
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: {{ printf "%s-updater" (include "digitalocean-dyndns.fullname" . ) }}
                      items:
                        - key: {{ template "digitalocean-dyndns.scriptName" . }}
                          path: {{ template "digitalocean-dyndns.scriptName" . }}
{{- end -}}
