{{- if and .Values.secret.create (empty .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "digitalocean-dyndns.fullname" .) }}
  labels:
    {{- include "digitalocean-dyndns.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DO_TOKEN: {{ .Values.secret.token | b64enc }}
{{- end -}}
