apiVersion: v2
type: application
name: cloudflared
description: A Helm chart for cloudflared DNS over HTTPS tunnel.
version: 1.5.1
# renovate: image=ghcr.io/crazy-max/cloudflared
appVersion: "2022.12.1"

home: https://charts.pascaliske.dev/charts/cloudflared/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/crazy-max/docker-cloudflared
keywords:
  - cloudflared
  - dns-over-https
  - dns-proxy
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
