apiVersion: v2
type: application
name: cloudflared
description: A Helm chart for cloudflared DNS over HTTPS tunnel.
version: 1.0.1
appVersion: "2021.8.7"

home: https://github.com/pascaliske/helm-charts
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/crazy-max/docker-cloudflared
keywords:
  - cloudflared
  - dns-over-https
  - dns-proxy
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
