apiVersion: v2
type: application
name: cloudflared
description: A Helm chart for cloudflared DNS over HTTPS tunnel.
version: 1.1.0
appVersion: "2022.1.0"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/cloudflared
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/crazy-max/docker-cloudflared
keywords:
  - cloudflared
  - dns-over-https
  - dns-proxy
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
