apiVersion: v2
type: application
name: cloudflare-dyndns
description: A Helm chart for a CronJob based Cloudflare DynDNS client.
version: 0.1.0
appVersion: "0.1.0"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/cloudflare-dyndns
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/pascaliske/docker-cloudflare-dyndns
keywords:
  - cloudflare
  - dyndns
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
