{{- if .Values.service.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "cloudflared.fullname" .) }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- with .Values.service.metrics.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
    service: {{ printf "%s-metrics" (include "cloudflared.fullname" .) }}
  {{- with .Values.service.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.metrics.type }}
  ports:
    {{- with .Values.service.metrics }}
    {{- if .enabled }}
    - name: metrics
      port: {{ .port }}
      targetPort: metrics
      {{- if and (eq $.Values.service.metrics.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: TCP
    {{- end }}
    {{- end }}
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
{{- end }}
