name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # create pages for docs
      - name: Create pages for docs
        run: |
          echo "---\nhide:\n  - navigation\n---\n" > docs/index.md
          cat README.md >> docs/index.md
          echo "---\nhide:\n  - navigation\n---\n" > docs/LICENSE.md
          cat LICENSE.md >> docs/LICENSE.md
          for chart in charts/*; do cp $chart/README.md docs/$chart.md; done

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
