name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**/Chart.yaml'
      - 'README.md'

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup helm
      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      # configure git
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # release charts
      - uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_repo_url: "${{ secrets.REPO_URL }}"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"

      # create pages for docs
      - name: Create pages for docs
        run: |
          echo "---\nhide:\n  - navigation\n---\n" > docs/home.md
          cat README.md >> docs/home.md
          echo "---\nhide:\n  - navigation\n---\n" > docs/LICENSE.md
          cat LICENSE.md >> docs/LICENSE.md
          for chart in charts/*; do cp $chart/README.md docs/$chart.md; done

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
