name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup helm
      - uses: azure/setup-helm@v3.0
        with:
          version: v3.8.1

      # configure git
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # create pages for docs
      - name: Create pages for docs
        run: |
          echo "---" > docs/index.md
          echo "hide:" >> docs/index.md
          echo "  - navigation" >> docs/index.md
          echo "---" >> docs/index.md
          cat README.md >> docs/index.md

          echo "---" > docs/LICENSE.md
          echo "hide:" >> docs/LICENSE.md
          echo "  - navigation" >> docs/LICENSE.md
          echo "---" >> docs/LICENSE.md
          cat LICENSE.md >> docs/LICENSE.md

          for chart in charts/*; do cp $chart/README.md docs/$chart.md; done

      # deploy charts
      - uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_SKIP_EXISTING: "true"

      # copy chart index to docs folder
      - name: Copy chart index to docs folder
        run: |
          cp -f .cr-index/index.yaml docs/index.yaml || curl https://${{ secrets.PROD_DOMAIN }}/index.yaml --output docs/index.yaml

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
